# Generated by Django 3.2.12 on 2022-04-18 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Association',
        ),
    ]
