# Generated by Django 3.2.13 on 2022-05-19 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220513_1321'),
        ('associations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='rank_avg',
            field=models.FloatField(default=1),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(default=1)),
                ('association', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.helpouser')),
            ],
        ),
    ]
