# Generated by Django 3.2.13 on 2022-05-19 11:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0002_auto_20220519_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='rank_avg',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='rank',
            name='rank',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
