# Generated by Django 3.2.12 on 2022-04-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0005_association'),
    ]

    operations = [
        migrations.AddField(
            model_name='association',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
