# Generated by Django 4.0.3 on 2022-04-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_privacy_user_high_privacy'),
        ('associations', '0006_association_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='volunteeringRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(max_length=500)),
                ('association', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.helpouser')),
            ],
        ),
    ]
