# Generated by Django 4.0.3 on 2022-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0007_volunteeringrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
