# Generated by Django 4.0.3 on 2022-04-22 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_helpo_user'),
        ('associations', '0008_alter_association_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='association',
            name='info',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='association',
            name='manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.associationmanager'),
        ),
        migrations.AlterField(
            model_name='association',
            name='vol_num',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
