# Generated by Django 4.0.3 on 2022-04-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0009_alter_association_email_alter_association_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='apartment',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='association',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='association',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='association',
            name='street',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
