# Generated by Django 3.2.13 on 2022-05-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_reports_counter'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpouser',
            name='deleted_posts',
            field=models.IntegerField(default=0),
        ),
    ]
