# Generated by Django 3.2.12 on 2022-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_helpouser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.BooleanField(default=False),
        ),
    ]
