# Generated by Django 3.2.13 on 2022-05-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helpouser_deleted_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_date',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='blocked_reason',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
