# Generated by Django 3.2.12 on 2022-04-13 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_privacy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='privacy',
            new_name='high_privacy',
        ),
    ]
