# Generated by Django 3.2.12 on 2022-04-01 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Naknik',
        ),
    ]
