# Generated by Django 3.2.13 on 2022-05-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('associations', '0003_auto_20220519_1137'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('asso', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='associations.association')),
            ],
        ),
    ]
