# Generated by Django 4.0.3 on 2022-04-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('posts', '0010_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, choices=[(1, 'קטגוריה 1'), (2, 'קטגוריה 2')], default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.category'),
        ),
    ]
