# Generated by Django 4.0.3 on 2022-04-24 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_post_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
